### ISSUE TITLE
createOptModel! throws "key :M not found"

### ISSUE THREAD

**Issue by mariok90** [leonardgoeke/anyMOD.jl#16]
I tried to transfer one of my models into the framwork and ran into these issues:

1. If none of my technologie has a mode, `createOptModel!` throws an `key :M not found` error.
2. So far, the framework does not seem to support specificing more than 9 pairs of parameter/value columns within an input file.
3. `setObjective!` throws the following error: `column(s) val are missing from argument(s)` I've added the model files to the issue.

I used the following data set:
[data.zip](https://github.com/leonardgoeke/anyMOD.jl/files/4230272/data.zip)

**Comment by leonardgoeke** [comment]
@mariok90 Bugs were fixed in new master branch,.
